name: CI

on:
  push:
  schedule:
    - cron: '0 6 * * *'

jobs:
  run:
    name: Pangeo-Forge CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Setup Python
        uses: actions/setup-python@v2.1.3
        with:
          python-version: 3.7
          architecture: x64
      - name: Install dependencies
        run: |
            python -m pip install -r requirements.txt
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        env:
          url_endpoint: https://www.us-east-2.wasabisys.com
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-region: us-east-2

      - name: Run Pipeline
        run: |
            # Login
            prefect backend cloud
            prefect auth login --token ${{ secrets.PREFECT_ACCESS_TOKEN }}
            export PREFECT__CLOUD__AGENT__AUTH_TOKEN=${{ secrets.PREFECT_CLOUD_AGENT_AUTH_TOKEN }}
            # prefect agent local start &
            # Register flow
            python pipeline.py
#            prefect run flow --name=Hydat-ETL --project=hydat-file-upload

