name: CI

on:
  push:
  schedule:
    - cron: '0 6 * * *'

jobs:
  run:
    name: Hydat-Forge Data Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Setup Python
        uses: actions/setup-python@v2.1.3
        with:
          python-version: 3.7
          architecture: x64
      - name: Install dependencies
        run: |
            python -m pip install -r requirements.txt
      - name: Configure AWS keys (Wasabi Sys.)
        run: |
            mkdir -p ~/.aws
            touch ~/.aws/credentials
            echo "
            [default]
            aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_access_key = ${{ secrets.AWS_SECRET_KEY_ID }}
            region = us-east-2
            source_profile = default" > ~/.aws/credentials
      - name: Run Pipeline
        run: |
            # Login
            prefect backend cloud
            export PREFECT__CLOUD__AGENT__AUTH_TOKEN=${{ secrets.PREFECT_CLOUD_AGENT_AUTH_TOKEN }}
            prefect auth login --token ${{ secrets.PREFECT_ACCESS_TOKEN }}
            # Register flow
            python pipeline.py
            aws s3 sync ./pipeline/data/zarr s3://hydrology/timeseries/sources/hydat/values.zarr --endpoint-url=https://www.s3.us-east-1.wasabisys.com --region=us-east-1 --profile=default