name: CI

on:
  push:
    branches: "master"

jobs:
  run:
    name: Pangeo-Forge CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Setup Python
        uses: actions/setup-python@v2.1.3
        with:
          python-version: 3.7
          architecture: x64
      - uses: actions/cache@v2.1.1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/*requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
            python -m pip install -r requirements.txt
      - name: Run Pipeline
        run: |
            # Login
            prefect auth login --token ${{ secrets.PREFECT_ACCESS_TOKEN }}
            export PREFECT__CLOUD__AGENT__AUTH_TOKEN=${{ secrets.PREFECT_CLOUD_AGENT_AUTH_TOKEN }}
            # Register flow
            python pipeline.py
            # Run flow
            prefect run flow --project=hydat-file-upload